wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1680009046.964833
    t:
      1:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.9.13
      5: 0.13.10
      8:
      - 3
      - 5
ac_dim:
  desc: null
  value: 2
env:
  desc: null
  value: CartPole-v1
episodes:
  desc: null
  value: 10000
epsilon:
  desc: null
  value: 0.1
eval_frequency:
  desc: null
  value: 25
gamma:
  desc: null
  value: 0.99
lr:
  desc: null
  value: 0.8
ob_dim:
  desc: null
  value: 4
wandb_name:
  desc: null
  value: CartPole-v1
