wandb_version: 1

env:
  desc: null
  value: Acrobot-v1
ac_dim:
  desc: null
  value: 3
ob_dim:
  desc: null
  value: 6
lr:
  desc: null
  value: 0.8
epsilon:
  desc: null
  value: 0.1
gamma:
  desc: null
  value: 0.99
wandb_name:
  desc: null
  value: Acrobot-v1
episodes:
  desc: null
  value: 10000
eval_frequency:
  desc: null
  value: 50
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1692692917.518827
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 16
      - 23
      4: 3.11.4
      5: 0.15.4
      8:
      - 3
      - 5
